package com.timemachine.replay;

public enum ReplayStatus {
    CREATED,
    ACQUIRING_RESOURCES,
    RESTORING_DATABASE,
    STARTING_MOCK_LAYER,
    REPLAYING_EVENTS,
    COLLECTING_TRACE,
    ANALYZING,
    COMPLETE,
    FAILED_RESTORE_VALIDATION,
    FAILED_ORDERING_VIOLATION,
    FAILED_BRANCH_CREATION,
    FAILED_CAUSAL_CYCLE,
    FAILED
}
